#!/bin/bash
#SBATCH --job-name=cellranger
#SBATCH --nodes=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=64G
#SBATCH --time=12:00:00
#SBATCH --output=/lisc/data/scratch/molevo/goeb/logs/blast.%j.log
#SBATCH --error=/lisc/data/scratch/molevo/goeb/logs/blast.%j.err
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=mayline.goeb@univie.ac.at

### ENVIRONMENT
module load BLAST+
module list

### VARIABLES
wd="/lisc/data/scratch/molevo/goeb"
od="/lisc/data/scratch/molevo/goeb/Nv2_blastn/blast-results.tsv"
db="/lisc/data/scratch/molevo/goeb/Nv2_blastn/Nv2_blastn_genome_db" ### database was made with Nv2 and makeblastdb command
QUERY="$wd/to_blast/FOXA4_T7.fasta"
###EXECUTION
blastn -query "$QUERY" -db $db -out "$od" -evalue 1e-5 -outfmt 6

#extract the coordinates and look at the annotation on simrbase

