#!/bin/bash
#SBATCH --job-name=cellranger
#SBATCH --nodes=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=64G
#SBATCH --time=12:00:00
#SBATCH --output=/lisc/data/scratch/course/2025w300106/goeb/logs/cellranger.%j.log
#SBATCH --error=/lisc/data/scratch/course/2025w300106/goeb/logs/cellranger.%j.err
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=mayline.goeb@univie.ac.at

### ENVIRONMENT
module load CellRanger
module list

### VARIABLES
wd="/lisc/data/scratch/course/2025w300106"
od="/lisc/data/scratch/course/2025w300106/goeb/results/cellranger"
indexDir="${wd}/common/NV2_fluo"
fastqDir="${wd}/common/blastula.12h/run1,${wd}/common/blastula.12h/run2,${wd}/common/blastula.12h/run3"
sample="89085"
## read all the fastq files cited with sample name including 89085
id="blastula_12h"

###EXECUTION
mkdir -p ${od}
cd ${od}
cellranger count --localcores 16 --transcriptome $indexDir --fastqs $fastqDir --id $id --sample $sample --create-bam false --force-cells 10000 --nosecondary
## force-cells 10 000: count until reaching 10K cells (remove the background)
## nosecondary : Disable secondary analysis, e.g. clustering (relevant for bulkRNAseq but not sc)
