#!/bin/bash
#SBATCH --job-name=fastqc
#SBATCH --nodes=1
#SBATCH --cpus-per-task=2
#SBATCH --mem=2G
#SBATCH --time=1:00:00
#SBATCH --output=/lisc/data/scratch/course/2025w300106/goeb/logs/fastqc.%j.log
#SBATCH --error=/lisc/data/scratch/course/2025w300106/goeb/logs/fastqc.%j.err
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=mayline.goeb@univie.ac.at

### ENVIRONMENT
module load FastQC
module list

### VARIABLES
outDir="/lisc/data/scratch/course/2025w300106/goeb/results/fastqc"
readsDir="/lisc/data/scratch/course/2025w300106/goeb"

### EXECUTION
echo "Started job at $(date)"
mkdir $outDir
fastqc $readsDir/SRR33559462_2.fastq $readsDir/SRR33559462_1.fastq -t 2 -f fastq -o $outDir
echo "Job finished at $(date)"
